### ISSUE TITLE
Вынести юнит-тесты в фолдер tests

### ISSUE THREAD

**Issue by lananolana** [lananolana/webpulse#16]

**Comment by psevdocoder** [comment]
Я слабо знаком, как в других языках программирования пишут и оформляют юнит тесты, но в Go принято их оставлять в том пакете, который они тестируют. Поискал несколько аргументов в пользу этого негласного правила на сайте Go:
> Testing from the inside
Most tests are compiled as part of the package under test.
This means they can access unexported details, as we have already seen

> Testing from the outside
Occasionally you want to run your tests from outside the package under test.
(Test files as package foo_test instead of package foo.)
This can break dependency cycles. For example:
The testing package uses fmt.
The fmt tests must import testing.
So the fmt tests are in package fmt_test and can import both testing and fmt.

https://go.dev/talks/2014/testing.slide#20
